erDiagram

    DEVICES {
        string deviceId PK
        string type
        string brand
        string model
        string serialNumber
        string location
        string status
        int batteryLevel
        boolean online
        boolean isOn
        date installationDate
        date lastUpdate
        string name
    }

    user_registration {
        string deviceId FK
        varchar passwor
        string email
    }
    LIGHT {
        string deviceId FK
        int brightness
        string color
        string mode
    }

    THERMOSTAT {
        string deviceId FK
        float temperature
        float humidity
        float targetTemperature
        string mode
        boolean ecoMode
    }

    LOCK {
        string deviceId FK
        boolean locked
        string lockType
        boolean autoLock 
    }

    LOCK_SECURITY {
        string deviceId FK
        string encryptedAccessCode
        date lastRotation
    }

    TV {
        string deviceId FK
        int volume
        string resolution
        string inputSource
    }

    AIR_CONDITIONER {
        string deviceId FK
        float temperature
        string mode
        boolean ecoMode
    }

    COMPUTER {
        string deviceId FK
        string operatingSystem
        int ramGB
        int storageGB
    }

    SPEAKER {
        string deviceId FK
        int volume
        boolean muted
        string connectivity
    }
    DEVICES ||--o{ user_registration : es
    DEVICES ||--o{ LIGHT : es
    DEVICES ||--o{ THERMOSTAT : es
    DEVICES ||--o{ LOCK : es
    DEVICES ||--o{ TV : es
    DEVICES ||--o{ AIR_CONDITIONER : es
    DEVICES ||--o{ COMPUTER : es
    DEVICES ||--o{ SPEAKER : es
    LOCK ||--|| LOCK_SECURITY : protege
